add jupyter to full and notebooks reqs
oxfordinternetinstitute/oxonfair pull request #30
Opened 2024-06-23 15:14 UTC by KaiRawal

I tried pip installing the [full] and [notebooks] versions of oxonfair in empty envs, and realised i needed to install jupyter separately.

2024-06-23 16:48 UTC, KaiRawal commented
@ChrisMRuss @e-delaney not sure how to add people as reviewers to PRs - perhaps we need to add everyone to this org or fiddle around in the GH settings? Would also be good to add automatic CI tests on each PR.

2024-06-24 09:23 UTC, ChrisMRuss requested changes
We only need one of these.
Please remove the duplicate entry from notebook_requirements.

2024-06-24 14:38 UTC, KaiRawal commented
Fixed.

2024-06-24 15:01 UTC, ChrisMRuss approved these changes

2024-06-24 15:01 UTC, merged